// Created by Crowbar 0.74

$modelname "kouoaeha\weapons\Ruger Mini-14 GB round (,223 Remington).mdl"

$bodygroup "Body"
{
	studio "mini14round.smd"
}


$surfaceprop "metal"

$contents "solid"

$illumposition 0 -0.005 0.026

$ambientboost

$mostlyopaque

$cdmaterials "models\kouoaeha\weapons\"

$cbox 0 0 0 0 0 0

$bbox -1.015 -0.17 -0.146 1.026 0.17 0.199


$sequence "Idle" {
	"ruger mini-14 gb round (,223 remington)_anims\Idle.smd"
	activity "ACT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}
